services:
  craiyon-bot:
    build: .
    environment:
      TDLIB_COMMIT_HASH: 889bdf06029f98f3d04cac874dafab6f4f847c47
      USER_AGENT:
      TELEGRAM_TOKEN:
      API_ID:
      API_HASH:
      DB_ENCRYPTION_KEY:
      COBALT_INSTANCES:
      OPENROUTER_API_KEY:
      FAL_API_KEY:
      STABLEHORDE_TOKEN:
      STABLEHORDE_CLIENT:
      MAKERSUITE_API_KEY:
      GROQ_API_KEY:
    networks:
      - cobalt-api
    volumes:
      - craiyon-bot:/data

networks:
  cobalt-api:
    external: true

volumes:
  craiyon-bot:
